### ISSUE TITLE
items can be fetched but no match

### ISSUE THREAD

**Issue by Hannes-Ole** [brazil-data-cube/rstac#50]
Maybe this is a bug or maybe I am just confused about what "matched" and "fetched" mean: Following the example on your README.md I figured that a `get_request()` on a `stac_search()` retrieves all possible matches (`items_matched`) and fetches the first 10 (`items_fetched`).
In that understanding it makes no sense, that I have a `stac_search()` that produces 0 matches (`items_matched = NULL`) but fetches 1 entry (`items_length = 1`)

Here is a reproducible example with my corresponding console output:
    
    it_obj <-
      stac("https://data.geo.admin.ch/api/stac/v0.9") %>%
      stac_search(collections = "ch.swisstopo.swisssurface3d", 
                  bbox = c(7.97302393965628,47.12855624467,7.97665224977385,47.129652366252)) %>%
      get_request()
    
    it_obj %>% items_fetch()
        ###STACItemCollection
        # - features (1 item(s)):
        #  - swisssurface3d_2020_2640-1219
        # - field(s): type, timeStamp, features, links

    it_obj %>% items_length()
        # [1] 1
    it_obj %>% items_matched()
       # NULL

The stac_search correctly identifies out of the thousands of tiles the swisssurface3D tile that corresponds to the bounding box (swisssurface3d_2020_2640-1219, see [here](https://s.geo.admin.ch/92136b7dce)) - what I understand, it is matched. How can that be and yet `items_matched = NULL`? What I want in the end is downloading the asset 

    download_items <- it_obj %>% 
      assets_download(assets_name = "swisssurface3d_2020_2640-1219_2056_5728.las.zip")

but that errors because of `items_matched = NULL`...

**Comment by OldLipe** [comment]
Hello @Hannes-Ole. 

The function `items_matched` returns the count of total number of results that 
match for your query. If the STAC API version is greater than or equal to 0.9.0,
 the **rstac** package searches for the [context](https://github.com/radiantearth/stac-api-spec/blob/master/fragments/context/README.md#context-object) fragment to return the number of items 
that were matched in your request.

See a reproducible example with the AWS STAC:

``` r
library(rstac)
library(magrittr)

# creating a query expression and making a requistion
items_aws <- rstac::stac("https://earth-search.aws.element84.com/v0/") %>%
    rstac::stac_search(.,
                       collections =  "sentinel-s2-l2a",
                       datetime = "2019-01-01/2019-12-31",
                       bbox = c("xmin" = 17.379,
                                "ymin" = 1.1573,
                                "xmax" = 17.410,
                                "ymax" = 1.1910),
                       limit = 25) %>%
    rstac::post_request()

# the number of items matched in query expression
rstac::items_matched(items_aws)
#> [1] 75

# the number of items that were returned in the search (according to limit = 25)
rstac::items_length(items_aws)
#> [1] 25

# get the all items matched in query expression doing pagination
rstac::items_fetch(items_aws, progress = FALSE) %>%
    rstac::items_length(.)
#> [1] 75
```

See that in your search query, only 1 item was returned and the number of items 
that were found in the search, as you mentioned, is null. Because the download 
function (`assets_download`) uses this information to notify the user that more 
items were found in the search the error occurred. 

What we can do is to return a warning telling the user that it was not 
possible to find the context fragment and let the download take place. 

As shown below:
``` r
library(rstac)
library(magrittr)

items_returned <- rstac::stac("https://data.geo.admin.ch/api/stac/v0.9") %>%
  rstac::stac_search(collections = "ch.swisstopo.swisssurface3d",
                     bbox = c(7.97302393965628,47.12855624467,7.97665224977385,47.129652366252)) %>%
  rstac::get_request()

rstac::assets_download(items_returned,
                       assets_name = "swisssurface3d_2020_2640-1219_2056_5728.las.zip",
                       output_dir = tempdir())
#> Warning: Items matched not provided.
#> Warning: It was not possible to return the number of items matched in your
#> search.
#>   |                                                          |                                                  |   0%  |                                                          |==================================================| 100%
#> ###STACItemCollection
#> - features (1 item(s)):
#>   - swisssurface3d_2020_2640-1219
#> - field(s): type, timeStamp, features, links
```

Now here is an example of using the paging function (`items_fetch`) through your
 example (change error to warning with new modifications on rstac):

``` r
library(rstac)
library(magrittr)

# creating a query expression and making a requistion
items_geo <- rstac::stac("https://data.geo.admin.ch/api/stac/v0.9") %>%
  rstac::stac_search(.,
                     collections = "ch.swisstopo.swisssurface3d",
                     datetime = "2015-01-01/2015-12-31",
                     limit = 10) %>%
  rstac::get_request()


# the number of items that were returned in the search (according to limit = 10)
rstac::items_length(items_geo)
#> [1] 10

# get the all items matched in query expression doing pagination
rstac::items_fetch(items_geo, progress = FALSE) %>%
  rstac::items_length(.)
#> Warning: Items matched not provided.
#> [1] 55
```

We will keep you informed as soon as we release this update in the development 
branch (which will take no more than one week).
